//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerScope.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerScope.Properties.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The information of characters nearby, characters on the player search window and the retainers you browse on the marketboard will be uploaded to the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgAgreement1 {
            get {
                return ResourceManager.GetString("AgAgreement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This information may include a wide range of details, such as character IDs, character customizations, character locations and retainer informations. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgAgreement2 {
            get {
                return ResourceManager.GetString("AgAgreement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just as you can see the data uploaded by other users, the data you upload will also be visible to other users. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgAgreement3 {
            get {
                return ResourceManager.GetString("AgAgreement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   However, you can change the visibility of your characters in the privacy settings under the My &apos;Characters &amp; Privacy&apos; tab, allowing you to hide the details of your characters from other users. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgAgreement4 {
            get {
                return ResourceManager.GetString("AgAgreement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin Consent - Upon connecting to the server, you consent to the following conditions: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgAgreementTitle {
            get {
                return ResourceManager.GetString("AgAgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   • This plugin operates on a crowdsourced model, meaning it relies on contributions from the player community to function and improve. Every player using the plugin contributes data, which helps build a more comprehensive and accurate dataset for everyone. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgCrowsourcedDescription {
            get {
                return ResourceManager.GetString("AgCrowsourcedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you accept the terms of the plugin? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgDoYouAccept {
            get {
                return ResourceManager.GetString("AgDoYouAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Alt Account Detection: The plugin automatically detects and links alt accounts of uploaded characters. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature1 {
            get {
                return ResourceManager.GetString("AgFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Name and HomeWorld History: Keeps a record of all the names a character has previously used and the world transfers they have made. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature2 {
            get {
                return ResourceManager.GetString("AgFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retainer History &amp; Marketboard UI: Records all changes made to a character&apos;s retainers, links the retainer with its owner and displays the owner&apos;s name when browsing the market board. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature3 {
            get {
                return ResourceManager.GetString("AgFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location History: Records the last known location of a character and keeps a history of the maps they’ve visited. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature4 {
            get {
                return ResourceManager.GetString("AgFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customization History: Records all changes to a character&apos;s customizations. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature5 {
            get {
                return ResourceManager.GetString("AgFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It also shows the date when all this information was added to the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgFeature6 {
            get {
                return ResourceManager.GetString("AgFeature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I agree that the information of characters around me, the characters on the player search menu
        ///and the retainers I see while browsing the marketboard will be uploaded to the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgIAgreeCheckBox {
            get {
                return ResourceManager.GetString("AgIAgreeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server-Based Features: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AgServerBasedFeatures {
            get {
                return ResourceManager.GetString("AgServerBasedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile refreshed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApiProfileRefreshed {
            get {
                return ResourceManager.GetString("ApiProfileRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service Unavailable benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApiServiceUnavailable {
            get {
                return ResourceManager.GetString("ApiServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stats refreshed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApiStatsRefreshed {
            get {
                return ResourceManager.GetString("ApiStatsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Found: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApiTotalFound {
            get {
                return ResourceManager.GetString("ApiTotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open UI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CmOpenUI {
            get {
                return ResourceManager.GetString("CmOpenUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to Favorites benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtAddToFavorites {
            get {
                return ResourceManager.GetString("DtAddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt Characters: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtAltCharacters {
            get {
                return ResourceManager.GetString("DtAltCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BustSize benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtBustSize {
            get {
                return ResourceManager.GetString("DtBustSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character last seen in: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtCharacterLastSeenIn {
            get {
                return ResourceManager.GetString("DtCharacterLastSeenIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtCharacterName {
            get {
                return ResourceManager.GetString("DtCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters of the player: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtCharactersOfThePlayer {
            get {
                return ResourceManager.GetString("DtCharactersOfThePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customization History benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtCustomizationHistory {
            get {
                return ResourceManager.GetString("DtCustomizationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtDuration {
            get {
                return ResourceManager.GetString("DtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetch Detailed Character Info From Server benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtFetchDetailedCharacterInfo {
            get {
                return ResourceManager.GetString("DtFetchDetailedCharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Seen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtFirstSeen {
            get {
                return ResourceManager.GetString("DtFirstSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtHeight {
            get {
                return ResourceManager.GetString("DtHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HomeWorld History: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtHomeworldHistory {
            get {
                return ResourceManager.GetString("DtHomeworldHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Seen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtLastSeen {
            get {
                return ResourceManager.GetString("DtLastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtLoading {
            get {
                return ResourceManager.GetString("DtLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location History benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtLocationHistory {
            get {
                return ResourceManager.GetString("DtLocationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A total of {0} location history results are displayed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtLocationHistoryResultsAreDisplayed {
            get {
                return ResourceManager.GetString("DtLocationHistoryResultsAreDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtMapButton {
            get {
                return ResourceManager.GetString("DtMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MuscleMass benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtMuscleMass {
            get {
                return ResourceManager.GetString("DtMuscleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name History: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtNameHistory {
            get {
                return ResourceManager.GetString("DtNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtOwnerName {
            get {
                return ResourceManager.GetString("DtOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtPlayerInfo {
            get {
                return ResourceManager.GetString("DtPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gender - Race benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRaceInfo {
            get {
                return ResourceManager.GetString("DtRaceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRefreshProfile {
            get {
                return ResourceManager.GetString("DtRefreshProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from Favorites benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRemoveFromFavorites {
            get {
                return ResourceManager.GetString("DtRemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info-&gt; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRetainerInfo {
            get {
                return ResourceManager.GetString("DtRetainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retainer Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRetainerName {
            get {
                return ResourceManager.GetString("DtRetainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All retainers of the player: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtRetainersOfThePlayer {
            get {
                return ResourceManager.GetString("DtRetainersOfThePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Showing results for: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtShowingResultsFor {
            get {
                return ResourceManager.GetString("DtShowingResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtShowRetainers {
            get {
                return ResourceManager.GetString("DtShowRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show the date in detail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtShowTheDateDetail {
            get {
                return ResourceManager.GetString("DtShowTheDateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DtZoneName {
            get {
                return ResourceManager.GetString("DtZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AccCount benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnAccountCount {
            get {
                return ResourceManager.GetString("MnAccountCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnAccountId {
            get {
                return ResourceManager.GetString("MnAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added at benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnAddedAt {
            get {
                return ResourceManager.GetString("MnAddedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnById {
            get {
                return ResourceManager.GetString("MnById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnByName {
            get {
                return ResourceManager.GetString("MnByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnCharacter {
            get {
                return ResourceManager.GetString("MnCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnContentId {
            get {
                return ResourceManager.GetString("MnContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Bad search query benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnErrorBadSearchQuery {
            get {
                return ResourceManager.GetString("MnErrorBadSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: You are not connected to server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnErrorYouAreNotConnected {
            get {
                return ResourceManager.GetString("MnErrorYouAreNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Any Part of Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnFilterMatchAnyPartOfName {
            get {
                return ResourceManager.GetString("MnFilterMatchAnyPartOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home World benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnHomeWorldColumn {
            get {
                return ResourceManager.GetString("MnHomeWorldColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnId {
            get {
                return ResourceManager.GetString("MnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local PC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnLocalPC {
            get {
                return ResourceManager.GetString("MnLocalPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnName {
            get {
                return ResourceManager.GetString("MnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnNameComboBox {
            get {
                return ResourceManager.GetString("MnNameComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Main Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnOpenMainMenu {
            get {
                return ResourceManager.GetString("MnOpenMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Settings Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnOpenSettingsMenu {
            get {
                return ResourceManager.GetString("MnOpenSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Settings Menu to connect to Server benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnOpenSettingsMenutoconnect {
            get {
                return ResourceManager.GetString("MnOpenSettingsMenutoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OwnerContentId benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnOwnerContentId {
            get {
                return ResourceManager.GetString("MnOwnerContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This player is identified as a bot. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnPlayerIdentifiedAsBot {
            get {
                return ResourceManager.GetString("MnPlayerIdentifiedAsBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnRemove {
            get {
                return ResourceManager.GetString("MnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RetainerCount benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnRetainerCount {
            get {
                return ResourceManager.GetString("MnRetainerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnRetainers {
            get {
                return ResourceManager.GetString("MnRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnSearch {
            get {
                return ResourceManager.GetString("MnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnSearching {
            get {
                return ResourceManager.GetString("MnSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnServer {
            get {
                return ResourceManager.GetString("MnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnSource {
            get {
                return ResourceManager.GetString("MnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Stats benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTabLocalStats {
            get {
                return ResourceManager.GetString("MnTabLocalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Favorites benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTabMyFavorites {
            get {
                return ResourceManager.GetString("MnTabMyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Characters &amp; Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTabSearchCharacterAndRetainer {
            get {
                return ResourceManager.GetString("MnTabSearchCharacterAndRetainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter {0}&apos;s {1} here benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTextInputEnterHere {
            get {
                return ResourceManager.GetString("MnTextInputEnterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Characters benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTotalCharacters {
            get {
                return ResourceManager.GetString("MnTotalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnTotalRetainers {
            get {
                return ResourceManager.GetString("MnTotalRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnWorld {
            get {
                return ResourceManager.GetString("MnWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are connected. You can sync from the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MnYouAreConnected {
            get {
                return ResourceManager.GetString("MnYouAreConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A total of {0} characters of yours were found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StATotalOfCharsFound {
            get {
                return ResourceManager.GetString("StATotalOfCharsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As you are a verified user, you are authorized to send information and receive from the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StAuthorizeDescription {
            get {
                return ResourceManager.GetString("StAuthorizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCancelLogin {
            get {
                return ResourceManager.GetString("StCancelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can resynchronize in:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCanSyncAgainTime {
            get {
                return ResourceManager.GetString("StCanSyncAgainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCharacterCount {
            get {
                return ResourceManager.GetString("StCharacterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCharacterName {
            get {
                return ResourceManager.GetString("StCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCharacters {
            get {
                return ResourceManager.GetString("StCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking Status... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCheckingStatus {
            get {
                return ResourceManager.GetString("StCheckingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Server Status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StCheckServerStatus {
            get {
                return ResourceManager.GetString("StCheckServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to copy Account Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StClickToCopyAccountId {
            get {
                return ResourceManager.GetString("StClickToCopyAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to copy Content Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StClickToCopyContentId {
            get {
                return ResourceManager.GetString("StClickToCopyContentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can configure the privacy settings of your characters in this tab. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StConfigurePrivacyOfChars {
            get {
                return ResourceManager.GetString("StConfigurePrivacyOfChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StConnect {
            get {
                return ResourceManager.GetString("StConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not logged in.
        ///Please login with a character to continue. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StErrorLoginWithACharacter {
            get {
                return ResourceManager.GetString("StErrorLoginWithACharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Stopped fetching. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StErrorStoppedFetching {
            get {
                return ResourceManager.GetString("StErrorStoppedFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to fetch Characters. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StErrorUnableToFetchCharacters {
            get {
                return ResourceManager.GetString("StErrorUnableToFetchCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to fetch Retainers. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StErrorUnableToFetchRetainers {
            get {
                return ResourceManager.GetString("StErrorUnableToFetchRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched Character Info Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StFetchedCharacter {
            get {
                return ResourceManager.GetString("StFetchedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The total count of characters whose profile details you have viewed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StFetchedCharactersHint {
            get {
                return ResourceManager.GetString("StFetchedCharactersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching Characters... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StFetchingCharacters {
            get {
                return ResourceManager.GetString("StFetchingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching Complete. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StFetchingComplete {
            get {
                return ResourceManager.GetString("StFetchingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching Retainers... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StFetchingRetainers {
            get {
                return ResourceManager.GetString("StFetchingRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home World: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StHomeWorld {
            get {
                return ResourceManager.GetString("StHomeWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lang: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StLanguage {
            get {
                return ResourceManager.GetString("StLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Updated on: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StLastUpdatedOn {
            get {
                return ResourceManager.GetString("StLastUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StLoadDetails {
            get {
                return ResourceManager.GetString("StLoadDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login with Discord benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StLoginWithDiscord {
            get {
                return ResourceManager.GetString("StLoginWithDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My contributions ♥ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StMyContributions {
            get {
                return ResourceManager.GetString("StMyContributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [NAME NOT FOUND] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StNameNotFound {
            get {
                return ResourceManager.GetString("StNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONLINE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StOnline {
            get {
                return ResourceManager.GetString("StOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -   Permissions: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPermissions {
            get {
                return ResourceManager.GetString("StPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dont Appear in Search Results benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyDontAppearInSearchResults {
            get {
                return ResourceManager.GetString("StPrivacyDontAppearInSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your name will NOT appear in search results. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyDontAppearInSearchResultsTooltip {
            get {
                return ResourceManager.GetString("StPrivacyDontAppearInSearchResultsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Alt Characters benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideAltCharacters {
            get {
                return ResourceManager.GetString("StPrivacyHideAltCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None of your alt characters will be visible to other players in the detailed player window. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideAltCharactersTooltip {
            get {
                return ResourceManager.GetString("StPrivacyHideAltCharactersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Customization History benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideCustomizationHistory {
            get {
                return ResourceManager.GetString("StPrivacyHideCustomizationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other players will NOT be able to see your customization history. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideCustomizationHistoryTooltip {
            get {
                return ResourceManager.GetString("StPrivacyHideCustomizationHistoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Full Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideFullProfile {
            get {
                return ResourceManager.GetString("StPrivacyHideFullProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other players will NOT be able to see your profile.
        ///However, if they have seen you before, they can find you by searching in the Local PC section. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideFullProfileTooltip {
            get {
                return ResourceManager.GetString("StPrivacyHideFullProfileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Location History benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideLocationHistory {
            get {
                return ResourceManager.GetString("StPrivacyHideLocationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other players will NOT be able to see your location history. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideLocationHistoryTooltip {
            get {
                return ResourceManager.GetString("StPrivacyHideLocationHistoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideRetainers {
            get {
                return ResourceManager.GetString("StPrivacyHideRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None of your retainers will be visible to other players and will NOT appear in search results. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivacyHideRetainersTooltip {
            get {
                return ResourceManager.GetString("StPrivacyHideRetainersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   private characters benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivateCharacters {
            get {
                return ResourceManager.GetString("StPrivateCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   private retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StPrivateRetainers {
            get {
                return ResourceManager.GetString("StPrivateRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Profile Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRefreshProfileInfo {
            get {
                return ResourceManager.GetString("StRefreshProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request profile data from the server benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRefreshProfileInfoHint {
            get {
                return ResourceManager.GetString("StRefreshProfileInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Server Stats benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRefreshServerStats {
            get {
                return ResourceManager.GetString("StRefreshServerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retainer Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRetainerCount {
            get {
                return ResourceManager.GetString("StRetainerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retainers benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRetainers {
            get {
                return ResourceManager.GetString("StRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRole {
            get {
                return ResourceManager.GetString("StRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleAdmin {
            get {
                return ResourceManager.GetString("StRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Banned benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleBanned {
            get {
                return ResourceManager.GetString("StRoleBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ouch! Only &quot;verified members&quot; can send information and receive from the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleDescriptionNonVerified {
            get {
                return ResourceManager.GetString("StRoleDescriptionNonVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guest benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleGuest {
            get {
                return ResourceManager.GetString("StRoleGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Member benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleMember {
            get {
                return ResourceManager.GetString("StRoleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moderator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleMod {
            get {
                return ResourceManager.GetString("StRoleMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Owner benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleOwner {
            get {
                return ResourceManager.GetString("StRoleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verified Member benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleVerifiedMember {
            get {
                return ResourceManager.GetString("StRoleVerifiedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StRoleVip {
            get {
                return ResourceManager.GetString("StRoleVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Config benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSaveConfig {
            get {
                return ResourceManager.GetString("StSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save your configuration to server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSaveConfigTooltip {
            get {
                return ResourceManager.GetString("StSaveConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total number of searched Character &amp; Retainer names: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSearchedNames {
            get {
                return ResourceManager.GetString("StSearchedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The total number of character and retainer search count. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSearchedNamesHint {
            get {
                return ResourceManager.GetString("StSearchedNamesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Send &amp; Receive Data) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSendAndReceiveData {
            get {
                return ResourceManager.GetString("StSendAndReceiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Database Stats benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StServerDatabaseStats {
            get {
                return ResourceManager.GetString("StServerDatabaseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Ip benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StServerIp {
            get {
                return ResourceManager.GetString("StServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Status: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StServerStatus {
            get {
                return ResourceManager.GetString("StServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show my ids benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StShowMyIds {
            get {
                return ResourceManager.GetString("StShowMyIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your character&apos;s profile was last visited on: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StSomeoneVisitedYourProfile {
            get {
                return ResourceManager.GetString("StSomeoneVisitedYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Fetching benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StStopFetching {
            get {
                return ResourceManager.GetString("StStopFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Characters &amp; Privacy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StTabMyCharactersAndPrivacy {
            get {
                return ResourceManager.GetString("StTabMyCharactersAndPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Stats &amp; Sync benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StTabServerStatsAndSync {
            get {
                return ResourceManager.GetString("StTabServerStatsAndSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StTabUserInfo {
            get {
                return ResourceManager.GetString("StTabUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Visit Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StTotalVisitCount {
            get {
                return ResourceManager.GetString("StTotalVisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploaded Character Info Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedCharacterInfo {
            get {
                return ResourceManager.GetString("StUploadedCharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The count of character info changes you sent to the server
        ///who are already in the database but have different names or worlds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedCharacterInfoHint {
            get {
                return ResourceManager.GetString("StUploadedCharacterInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploaded Characters Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedCharacters {
            get {
                return ResourceManager.GetString("StUploadedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The total count of characters you sent to the server
        ///who were not previously in the database. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedCharactersHint {
            get {
                return ResourceManager.GetString("StUploadedCharactersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploaded Retainer Info Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedRetainerInfo {
            get {
                return ResourceManager.GetString("StUploadedRetainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The total count of retainer info changes (name or world) you sent to the server. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedRetainerInfoHint {
            get {
                return ResourceManager.GetString("StUploadedRetainerInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploaded Retainers Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedRetainers {
            get {
                return ResourceManager.GetString("StUploadedRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The total count of retainers you sent to the server
        ///who were not previously in the database. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUploadedRetainersHint {
            get {
                return ResourceManager.GetString("StUploadedRetainersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Count: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StUserCount {
            get {
                return ResourceManager.GetString("StUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Character and Retainer info from Server benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SyncCharacterAndRetainerFromServer {
            get {
                return ResourceManager.GetString("SyncCharacterAndRetainerFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayerScope Details Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleDetailsMenu {
            get {
                return ResourceManager.GetString("TitleDetailsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayerScope Main Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleMainMenu {
            get {
                return ResourceManager.GetString("TitleMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayerScope Server Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleSettingsMenu {
            get {
                return ResourceManager.GetString("TitleSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   about {0} {1} from now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsAboutFromNow {
            get {
                return ResourceManager.GetString("ToolsAboutFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   about {0} seconds from now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsAboutSecondsFromNow {
            get {
                return ResourceManager.GetString("ToolsAboutSecondsFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   day benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsDay {
            get {
                return ResourceManager.GetString("ToolsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   days benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsDays {
            get {
                return ResourceManager.GetString("ToolsDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hour benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsHour {
            get {
                return ResourceManager.GetString("ToolsHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hours benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsHours {
            get {
                return ResourceManager.GetString("ToolsHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   just now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsJustNow {
            get {
                return ResourceManager.GetString("ToolsJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minute benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsMinute {
            get {
                return ResourceManager.GetString("ToolsMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsMinutes {
            get {
                return ResourceManager.GetString("ToolsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   month benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsMonth {
            get {
                return ResourceManager.GetString("ToolsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   months benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsMonths {
            get {
                return ResourceManager.GetString("ToolsMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   second benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsSecond {
            get {
                return ResourceManager.GetString("ToolsSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsSeconds {
            get {
                return ResourceManager.GetString("ToolsSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} ago benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsTimeSinceAgo {
            get {
                return ResourceManager.GetString("ToolsTimeSinceAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} {2} minutes ago benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsTimeSinceMinutesAgo {
            get {
                return ResourceManager.GetString("ToolsTimeSinceMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} {2} seconds ago benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsTimeSinceSecondsAgo {
            get {
                return ResourceManager.GetString("ToolsTimeSinceSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsYear {
            get {
                return ResourceManager.GetString("ToolsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Years benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolsYears {
            get {
                return ResourceManager.GetString("ToolsYears", resourceCulture);
            }
        }
    }
}
